site_name: VRITRA-XD | SOC Analyst Portfolio
site_description: SOC Analyst, Detection Engineering and Malware Analysis
site_author: Anshuman Singh

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: cyan
nav:
  - Home: index.md

  - LetsDefend:
      - SOC001: letsdefend/sec001.md
      - SOC002: letsdefend/sec002.md
  - Malware-Analysis:
      - First: malware-analysis/anal.md
  - Blog: 
      - b01: blog/firstblog.md
  - About: Anshu.md